// <auto-generated />
namespace ABC_Leave_Portal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedareadonlyfield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedareadonlyfield));
        
        string IMigrationMetadata.Id
        {
            get { return "202010171351210_added a readonly field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
